### ISSUE TITLE
Bad Request in auth.py

### ISSUE THREAD

**Issue by pablo-lo** [Azure-Samples/mipsdk-protectionapi-cpp-sample-basic#1]
Hello,

when running the sample, I get the following output in the terminal:

Traceback (most recent call last):
  File "auth.py", line 114, in <module>
    main(sys.argv[1:])
  File "auth.py", line 108, in main
    f = urllib2.urlopen(req)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request

The VS debugger shows an unhandled exception in the file future, line 352. The details are
"Unhandled exception at 0x00007FFE173AA388 in mipsdk-protectionapi-cpp-sample-basic.exe: Microsoft C++ exception: mip::InternalError at memory location 0x0000002C232FEAA0. occurred"

I am using Python 2.7.15, Windows10 and VS Professional 2017. 
The commit hash of the sample is bbbac3ab1e625fae77dd6f61a708e9f30e705075.
The MIP SDK binaries were downloaded this week from here: https://www.microsoft.com/en-us/download/details.aspx?id=57392

The only modifications I have made are setting the ClientID and my Azure account data.
What could be the reason for this?

Thanks,
pablo

**Comment by pablo-lo** [comment]
Follow up: The problem was actually not in the python script, but in the credentials submitted, so the issue can be seen as closed.
